var elements2 = [{ group: 'nodes', data: { id: 'com.orchestral.esp.admin.metrics|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.medication.esp.ccda.service.internal|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.context|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.core|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.rest|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.patient|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.log.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.metrics|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.allergyintolerance.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.utility|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.documentreference.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir1.0-Rest|1.0.1.final' }  },
{ group: 'nodes', data: { id: 'configuration-admin-webservice|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.commonweb.taglib.stripes|7.5.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.encounter.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.relatedperson.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.rest|1.0.1.final' }  },
{ group: 'nodes', data: { id: 'medication-esp-ccda|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.template|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.medication|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.commonweb.taglib.ui|7.5.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.log.api_1|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.patient.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.common.esp.test|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'common-web|7.5.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.logging|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.task|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.servlet|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.configuration.admin.webservice|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.resourcetypehandler.patient.dstu2|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.healthlanguage.ui|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.event|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.rest|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'health-common-esp|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.blockly|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.acceptance.adapter.esp.rest|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.common.ccda.esp|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.medication.esp.ccda.space|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'Fhir-Utility|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.healthterm.ui|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'fhir-medication-resource|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.commonweb|7.5.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.puppetpatient.server|0.2.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.blockly.api|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.hibernate3|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.admin.ui.vaadin|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.dispense.dstu2|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.conformance|1.0.1.final' }  },
{ group: 'nodes', data: { id: 'esp-admin|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.ui|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.space.spi_1|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.acceptance.terminology.mock.healthterm|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.common.esp|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'esp-kernel|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.file|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.security|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.license|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.log|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.management.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.patient|1.2.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.patient.ui|1.2.2.final' }  },
{ group: 'nodes', data: { id: 'com.google.common|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.version|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir-1x-Resource-Type-Handler|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.metrics.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir-Patient|1.2.2.final' }  },
{ group: 'nodes', data: { id: 'Fhir-Rest|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'oin-blockly|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.ace|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.collection|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.space.api_1|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'clinical-terminology-service|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.medication.esp.ccda.mapper|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.careplan.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.admin.dstu2|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.rest.forwarder|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.yahoo.yui3|3.9.1.final' }  },
{ group: 'nodes', data: { id: 'Fhir1.0-Rest|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'ace-editor|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'tools-core|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.exception|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.ui.common|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.ws|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.statement.dstu2|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.apt|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.healthterm|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.management|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.space.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.medication.aggregation|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'health-common-ccda-esp|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.blockly.spi|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.conformance|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir-Core|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.stripes|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.commonweb.taglib.output|7.5.2.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.admin.vaadin|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'puppet-patient-server|0.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.blockly.web|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.api_1|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.webservices.client|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.health.medication.esp.ccda.ui|1.1.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.practitioner.dstu2|1.2.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.context|1.0.1.final' }  },
{ group: 'nodes', data: { id: 'health-terminology-dev|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.admin.ws|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.space|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.order.dstu2|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.terminology.healthlanguage|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.space.mapper.passthrough|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.utility|1.1.0.final' }  },
{ group: 'nodes', data: { id: 'Fhir1.0-Patient|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'yui-3|3.9.1.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.core.conformance.ui|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.conformance|1.0.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.1.final' }  },
{ group: 'nodes', data: { id: 'health-esp-acceptance|1.0.0.beta' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.date|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.data.ws|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.btree|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.common.diagnosis|7.1.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.esp.task.cassandra|1.5.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir.conformance.ui|1.3.0.final' }  },
{ group: 'nodes', data: { id: 'com.orchestral.openapi.fhir_1_0.context|1.0.0.final' }  },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl', source: 'Fhir1.0-Rest|1.0.1.final', target: 'odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-foundation|8.4.0.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-Fhir-Core|1.3.0.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'Fhir-Core|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-cDataAccess|8.12.0.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'cDataAccess|8.12.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-com.orchestral.openapi.fhir_1_0.context|1.0.1.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'com.orchestral.openapi.fhir_1_0.context|1.0.1.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-com.orchestral.openapi.fhir_1_0.conformance|1.0.1.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'com.orchestral.openapi.fhir_1_0.conformance|1.0.1.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.1.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.1.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.1.final-com.orchestral.openapi.fhir_1_0.rest|1.0.1.final', source: 'Fhir1.0-Rest|1.0.1.final', target: 'com.orchestral.openapi.fhir_1_0.rest|1.0.1.final' } },
{ group: 'edges', data: { id: 'configuration-admin-webservice|1.0.0.final-foundation|7.2.4.final', source: 'configuration-admin-webservice|1.0.0.final', target: 'foundation|7.2.4.final' } },
{ group: 'edges', data: { id: 'configuration-admin-webservice|1.0.0.final-com.orchestral.configuration.admin.webservice|1.0.0.final', source: 'configuration-admin-webservice|1.0.0.final', target: 'com.orchestral.configuration.admin.webservice|1.0.0.final' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-foundation|8.4.0.final', source: 'medication-esp-ccda|1.1.0.beta', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-health-common-ccda-esp|1.1.0.beta', source: 'medication-esp-ccda|1.1.0.beta', target: 'health-common-ccda-esp|1.1.0.beta' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-fhir-medication-resource|1.1.0.final', source: 'medication-esp-ccda|1.1.0.beta', target: 'fhir-medication-resource|1.1.0.final' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-com.orchestral.health.medication.esp.ccda.space|1.1.0.beta', source: 'medication-esp-ccda|1.1.0.beta', target: 'com.orchestral.health.medication.esp.ccda.space|1.1.0.beta' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-com.orchestral.health.medication.esp.ccda.service.internal|1.1.0.beta', source: 'medication-esp-ccda|1.1.0.beta', target: 'com.orchestral.health.medication.esp.ccda.service.internal|1.1.0.beta' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-com.orchestral.health.medication.esp.ccda.mapper|1.1.0.beta', source: 'medication-esp-ccda|1.1.0.beta', target: 'com.orchestral.health.medication.esp.ccda.mapper|1.1.0.beta' } },
{ group: 'edges', data: { id: 'medication-esp-ccda|1.1.0.beta-com.orchestral.health.medication.esp.ccda.ui|1.1.0.beta', source: 'medication-esp-ccda|1.1.0.beta', target: 'com.orchestral.health.medication.esp.ccda.ui|1.1.0.beta' } },
{ group: 'edges', data: { id: 'com.orchestral.health.common.esp.test|1.1.0.beta-org.junit|4.11.0', source: 'com.orchestral.health.common.esp.test|1.1.0.beta', target: 'org.junit|4.11.0' } },
{ group: 'edges', data: { id: 'com.orchestral.health.common.esp.test|1.1.0.beta-org.mockito|1.9.5', source: 'com.orchestral.health.common.esp.test|1.1.0.beta', target: 'org.mockito|1.9.5' } },
{ group: 'edges', data: { id: 'com.orchestral.health.common.esp.test|1.1.0.beta-assertj-core|3.4.1', source: 'com.orchestral.health.common.esp.test|1.1.0.beta', target: 'assertj-core|3.4.1' } },
{ group: 'edges', data: { id: 'com.orchestral.health.common.esp.test|1.1.0.beta-odl.com.google.common18|18.0.0.0-1-odl', source: 'com.orchestral.health.common.esp.test|1.1.0.beta', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-foundation|6.10.4.final', source: 'common-web|7.5.2.final', target: 'foundation|6.10.4.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-tools-core|5.23.0.final', source: 'common-web|7.5.2.final', target: 'tools-core|5.23.0.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-yui-2|2.8.10.final', source: 'common-web|7.5.2.final', target: 'yui-2|2.8.10.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-yui-3|3.9.1.final', source: 'common-web|7.5.2.final', target: 'yui-3|3.9.1.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-modernizr|2.5.3.0-5-odl', source: 'common-web|7.5.2.final', target: 'modernizr|2.5.3.0-5-odl' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-javax.mail|1.4.3', source: 'common-web|7.5.2.final', target: 'javax.mail|1.4.3' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-org.apache.commons.collections|3.2.0', source: 'common-web|7.5.2.final', target: 'org.apache.commons.collections|3.2.0' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-org.apache.commons.codec|1.3.0', source: 'common-web|7.5.2.final', target: 'org.apache.commons.codec|1.3.0' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-org.apache.commons.lang|2.2.0', source: 'common-web|7.5.2.final', target: 'org.apache.commons.lang|2.2.0' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-org.apache.taglibs.standard|1.1.2', source: 'common-web|7.5.2.final', target: 'org.apache.taglibs.standard|1.1.2' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-com.googlecode.jatl|0.1.0', source: 'common-web|7.5.2.final', target: 'com.googlecode.jatl|0.1.0' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-net.sourceforge.flexjson|1.9.2', source: 'common-web|7.5.2.final', target: 'net.sourceforge.flexjson|1.9.2' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-net.sourceforge.stripes|1.5.6', source: 'common-web|7.5.2.final', target: 'net.sourceforge.stripes|1.5.6' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-com.orchestral.commonweb.taglib.ui|7.5.2.final', source: 'common-web|7.5.2.final', target: 'com.orchestral.commonweb.taglib.ui|7.5.2.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-com.orchestral.commonweb|7.5.2.final', source: 'common-web|7.5.2.final', target: 'com.orchestral.commonweb|7.5.2.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-com.orchestral.commonweb.taglib.stripes|7.5.2.final', source: 'common-web|7.5.2.final', target: 'com.orchestral.commonweb.taglib.stripes|7.5.2.final' } },
{ group: 'edges', data: { id: 'common-web|7.5.2.final-com.orchestral.commonweb.taglib.output|7.5.2.final', source: 'common-web|7.5.2.final', target: 'com.orchestral.commonweb.taglib.output|7.5.2.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-foundation|8.4.0.final', source: 'health-common-esp|1.0.0.beta', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-cDataAccess|8.12.0.final', source: 'health-common-esp|1.0.0.beta', target: 'cDataAccess|8.12.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-esp-kernel|1.5.0.final', source: 'health-common-esp|1.0.0.beta', target: 'esp-kernel|1.5.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-esp-admin|1.5.0.final', source: 'health-common-esp|1.0.0.beta', target: 'esp-admin|1.5.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-clinical-terminology-service|1.3.0.final', source: 'health-common-esp|1.0.0.beta', target: 'clinical-terminology-service|1.3.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-tools-core|7.1.0.final', source: 'health-common-esp|1.0.0.beta', target: 'tools-core|7.1.0.final' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-odl.com.google.common18|18.0.0.0-1-odl', source: 'health-common-esp|1.0.0.beta', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-ca.uhn.hapi|1.2.0', source: 'health-common-esp|1.0.0.beta', target: 'ca.uhn.hapi|1.2.0' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl', source: 'health-common-esp|1.0.0.beta', target: 'odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl' } },
{ group: 'edges', data: { id: 'health-common-esp|1.0.0.beta-com.orchestral.health.common.esp|1.0.0.beta', source: 'health-common-esp|1.0.0.beta', target: 'com.orchestral.health.common.esp|1.0.0.beta' } },
{ group: 'edges', data: { id: 'Fhir-Utility|1.1.0.final-Fhir-Rest|1.2.0.final', source: 'Fhir-Utility|1.1.0.final', target: 'Fhir-Rest|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Utility|1.1.0.final-core|8.0.0.final', source: 'Fhir-Utility|1.1.0.final', target: 'core|8.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Utility|1.1.0.final-i12e-patient|8.12.0.final', source: 'Fhir-Utility|1.1.0.final', target: 'i12e-patient|8.12.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Utility|1.1.0.final-com.orchestral.openapi.fhir.utility|1.1.0.final', source: 'Fhir-Utility|1.1.0.final', target: 'com.orchestral.openapi.fhir.utility|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-arquillian-osgi|1.0.1', source: 'fhir-medication-resource|1.1.0.final', target: 'arquillian-osgi|1.0.1' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-Fhir1.0-Rest|1.0.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'Fhir1.0-Rest|1.0.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-core|8.4.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'core|8.4.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-i12e-patient|8.13.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'i12e-patient|8.13.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-cDataAccess|8.12.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'cDataAccess|8.12.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-org.apache.httpcomponents.httpclient|4.2.3-1-odl', source: 'fhir-medication-resource|1.1.0.final', target: 'org.apache.httpcomponents.httpclient|4.2.3-1-odl' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-org.apache.httpcomponents.httpcore|4.2.3-1-odl', source: 'fhir-medication-resource|1.1.0.final', target: 'org.apache.httpcomponents.httpcore|4.2.3-1-odl' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.resourcetypehandler.medication.admin.dstu2|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.admin.dstu2|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.resourcetypehandler.medication.statement.dstu2|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.statement.dstu2|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.resourcetypehandler.medication.order.dstu2|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.order.dstu2|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.resourcetypehandler.medication.dispense.dstu2|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.medication.dispense.dstu2|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.medication.aggregation|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.medication.aggregation|1.1.0.final' } },
{ group: 'edges', data: { id: 'fhir-medication-resource|1.1.0.final-com.orchestral.openapi.fhir.medication|1.1.0.final', source: 'fhir-medication-resource|1.1.0.final', target: 'com.orchestral.openapi.fhir.medication|1.1.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-Fhir-Rest|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'Fhir-Rest|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-Fhir-Utility|1.1.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'Fhir-Utility|1.1.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.careplan.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.careplan.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.practitioner.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.practitioner.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.documentreference.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.documentreference.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.allergyintolerance.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.allergyintolerance.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.relatedperson.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.relatedperson.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.patient.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.patient.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Resource-Type-Handler|1.2.0.final-com.orchestral.openapi.fhir.resourcetypehandler.encounter.dstu2|1.2.0.final', source: 'Fhir-Resource-Type-Handler|1.2.0.final', target: 'com.orchestral.openapi.fhir.resourcetypehandler.encounter.dstu2|1.2.0.final' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-esp-kernel|1.5.0.final', source: 'esp-admin|1.5.0.final', target: 'esp-kernel|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-odl.com.google.common18|18.0.0.0-1-odl', source: 'esp-admin|1.5.0.final', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-com.orchestral.esp.admin.metrics|1.5.0.final', source: 'esp-admin|1.5.0.final', target: 'com.orchestral.esp.admin.metrics|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-com.orchestral.esp.admin.ws|1.5.0.final', source: 'esp-admin|1.5.0.final', target: 'com.orchestral.esp.admin.ws|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-com.orchestral.esp.admin.vaadin|1.5.0.final', source: 'esp-admin|1.5.0.final', target: 'com.orchestral.esp.admin.vaadin|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-admin|1.5.0.final-com.orchestral.esp.admin.ui.vaadin|1.5.0.final', source: 'esp-admin|1.5.0.final', target: 'com.orchestral.esp.admin.ui.vaadin|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-foundation|8.0.0.final', source: 'esp-kernel|1.5.0.final', target: 'foundation|8.0.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.sun.xml.fastinfoset|1.2.13', source: 'esp-kernel|1.5.0.final', target: 'com.sun.xml.fastinfoset|1.2.13' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-org.eclipse.jdt.annotation|2.0.0', source: 'esp-kernel|1.5.0.final', target: 'org.eclipse.jdt.annotation|2.0.0' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-odl.com.google.common18|18.0.0.0-1-odl', source: 'esp-kernel|1.5.0.final', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.log.api_1|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.log.api_1|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.log|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.log|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.space.api_1|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.space.api_1|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.space.spi_1|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.space.spi_1|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.space|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.space|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.space.mapper.passthrough|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.space.mapper.passthrough|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.event|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.event|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.metrics|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.metrics|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.task|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.task|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.management|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.management|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.metrics.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.metrics.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.task.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.task.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.management.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.management.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.log.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.log.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.license|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.license|1.5.0.final' } },
{ group: 'edges', data: { id: 'esp-kernel|1.5.0.final-com.orchestral.esp.space.cassandra|1.5.0.final', source: 'esp-kernel|1.5.0.final', target: 'com.orchestral.esp.space.cassandra|1.5.0.final' } },
{ group: 'edges', data: { id: 'Fhir-1x-Resource-Type-Handler|1.0.0.final-Fhir-Utility|1.1.0.final', source: 'Fhir-1x-Resource-Type-Handler|1.0.0.final', target: 'Fhir-Utility|1.1.0.final' } },
{ group: 'edges', data: { id: 'Fhir-1x-Resource-Type-Handler|1.0.0.final-Fhir1.0-Rest|1.0.1.final', source: 'Fhir-1x-Resource-Type-Handler|1.0.0.final', target: 'Fhir1.0-Rest|1.0.1.final' } },
{ group: 'edges', data: { id: 'Fhir-1x-Resource-Type-Handler|1.0.0.final-com.orchestral.openapi.fhir_1_0.resourcetypehandler.patient.dstu2|1.0.0.final', source: 'Fhir-1x-Resource-Type-Handler|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.resourcetypehandler.patient.dstu2|1.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-foundation|8.2.0.final', source: 'Fhir-Patient|1.2.2.final', target: 'foundation|8.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-i12e-patient|8.12.0.final', source: 'Fhir-Patient|1.2.2.final', target: 'i12e-patient|8.12.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-Fhir-Rest|1.2.0.final', source: 'Fhir-Patient|1.2.2.final', target: 'Fhir-Rest|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-Fhir-Resource-Type-Handler|1.2.0.final', source: 'Fhir-Patient|1.2.2.final', target: 'Fhir-Resource-Type-Handler|1.2.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-org.apache.httpcomponents.httpclient|4.2.3-1-odl', source: 'Fhir-Patient|1.2.2.final', target: 'org.apache.httpcomponents.httpclient|4.2.3-1-odl' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-org.apache.httpcomponents.httpcore|4.2.3-1-odl', source: 'Fhir-Patient|1.2.2.final', target: 'org.apache.httpcomponents.httpcore|4.2.3-1-odl' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-cDataAccess|8.11.0.final', source: 'Fhir-Patient|1.2.2.final', target: 'cDataAccess|8.11.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-com.google.gson|2.2.4', source: 'Fhir-Patient|1.2.2.final', target: 'com.google.gson|2.2.4' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-com.orchestral.openapi.fhir.patient|1.2.2.final', source: 'Fhir-Patient|1.2.2.final', target: 'com.orchestral.openapi.fhir.patient|1.2.2.final' } },
{ group: 'edges', data: { id: 'Fhir-Patient|1.2.2.final-com.orchestral.openapi.fhir.patient.ui|1.2.2.final', source: 'Fhir-Patient|1.2.2.final', target: 'com.orchestral.openapi.fhir.patient.ui|1.2.2.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-odl.ca.uhn.fhir_1_0|1.0.0.0-4-odl', source: 'Fhir-Rest|1.3.0.final', target: 'odl.ca.uhn.fhir_1_0|1.0.0.0-4-odl' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-foundation|8.0.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'foundation|8.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-Fhir-Core|1.3.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'Fhir-Core|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-com.orchestral.openapi.fhir.context|1.3.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'com.orchestral.openapi.fhir.context|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-com.orchestral.openapi.fhir.conformance|1.3.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'com.orchestral.openapi.fhir.conformance|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-com.orchestral.openapi.fhir.conformance.ui|1.3.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'com.orchestral.openapi.fhir.conformance.ui|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Rest|1.3.0.final-com.orchestral.openapi.fhir.rest|1.3.0.final', source: 'Fhir-Rest|1.3.0.final', target: 'com.orchestral.openapi.fhir.rest|1.3.0.final' } },
{ group: 'edges', data: { id: 'oin-blockly|1.0.0.final-foundation|7.4.0.final', source: 'oin-blockly|1.0.0.final', target: 'foundation|7.4.0.final' } },
{ group: 'edges', data: { id: 'oin-blockly|1.0.0.final-com.orchestral.blockly.api|1.0.0.final', source: 'oin-blockly|1.0.0.final', target: 'com.orchestral.blockly.api|1.0.0.final' } },
{ group: 'edges', data: { id: 'oin-blockly|1.0.0.final-com.orchestral.blockly.web|1.0.0.final', source: 'oin-blockly|1.0.0.final', target: 'com.orchestral.blockly.web|1.0.0.final' } },
{ group: 'edges', data: { id: 'oin-blockly|1.0.0.final-com.orchestral.blockly.spi|1.0.0.final', source: 'oin-blockly|1.0.0.final', target: 'com.orchestral.blockly.spi|1.0.0.final' } },
{ group: 'edges', data: { id: 'oin-blockly|1.0.0.final-com.orchestral.blockly|1.0.0.final', source: 'oin-blockly|1.0.0.final', target: 'com.orchestral.blockly|1.0.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-foundation|7.10.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'foundation|7.10.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-org.apache.commons.jxpath|1.2.0.0-odl-1', source: 'clinical-terminology-service|1.3.0.final', target: 'org.apache.commons.jxpath|1.2.0.0-odl-1' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.ws|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.ws|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.webservices.client|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.webservices.client|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.ui.common|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.ui.common|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.api_1|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.api_1|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.healthterm|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.healthterm|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.ws|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.ws|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.healthterm.ui|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.healthterm.ui|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.healthlanguage|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.healthlanguage|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.healthlanguage.ui|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.healthlanguage.ui|1.3.0.final' } },
{ group: 'edges', data: { id: 'clinical-terminology-service|1.3.0.final-com.orchestral.data.terminology.ui|1.3.0.final', source: 'clinical-terminology-service|1.3.0.final', target: 'com.orchestral.data.terminology.ui|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl', source: 'Fhir1.0-Rest|1.0.0.final', target: 'odl.ca.uhn.fhir_1_2|1.2.0.0-1-odl' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-foundation|8.4.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-Fhir-Core|1.3.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'Fhir-Core|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-cDataAccess|8.12.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'cDataAccess|8.12.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-com.orchestral.openapi.fhir_1_0.context|1.0.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.context|1.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-com.orchestral.openapi.fhir_1_0.conformance|1.0.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.conformance|1.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.conformance.ui|1.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Rest|1.0.0.final-com.orchestral.openapi.fhir_1_0.rest|1.0.0.final', source: 'Fhir1.0-Rest|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.rest|1.0.0.final' } },
{ group: 'edges', data: { id: 'ace-editor|1.2.0.final-foundation|7.4.0.final', source: 'ace-editor|1.2.0.final', target: 'foundation|7.4.0.final' } },
{ group: 'edges', data: { id: 'ace-editor|1.2.0.final-odl.com.google.common18|18.0.0.0-1-odl', source: 'ace-editor|1.2.0.final', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'ace-editor|1.2.0.final-com.orchestral.ace|1.2.0.final', source: 'ace-editor|1.2.0.final', target: 'com.orchestral.ace|1.2.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-antlr|2.7.6', source: 'tools-core|7.1.0.final', target: 'antlr|2.7.6' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javassist|3.12.0', source: 'tools-core|7.1.0.final', target: 'javassist|3.12.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.dom4j|1.6.1', source: 'tools-core|7.1.0.final', target: 'org.dom4j|1.6.1' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.hibernate|3.6.10.1-odl', source: 'tools-core|7.1.0.final', target: 'org.hibernate|3.6.10.1-odl' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.hibernate.validator|4.1.0.1-odl', source: 'tools-core|7.1.0.final', target: 'org.hibernate.validator|4.1.0.1-odl' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.jaxen|1.1.0', source: 'tools-core|7.1.0.final', target: 'org.jaxen|1.1.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.jdom|1.0.0', source: 'tools-core|7.1.0.final', target: 'org.jdom|1.0.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.slf4j.api|1.6.1', source: 'tools-core|7.1.0.final', target: 'org.slf4j.api|1.6.1' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.resource|1.5.0', source: 'tools-core|7.1.0.final', target: 'javax.resource|1.5.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.servlet|2.4.0', source: 'tools-core|7.1.0.final', target: 'javax.servlet|2.4.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.ejb|3.0.0', source: 'tools-core|7.1.0.final', target: 'javax.ejb|3.0.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.persistence|20.1.0.1', source: 'tools-core|7.1.0.final', target: 'javax.persistence|20.1.0.1' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.transaction|1.1.0', source: 'tools-core|7.1.0.final', target: 'javax.transaction|1.1.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-javax.validation|1.0.0', source: 'tools-core|7.1.0.final', target: 'javax.validation|1.0.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.commons.collections|3.2.0', source: 'tools-core|7.1.0.final', target: 'org.apache.commons.collections|3.2.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.commons.lang|2.6.0.0-1-odl', source: 'tools-core|7.1.0.final', target: 'org.apache.commons.lang|2.6.0.0-1-odl' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.commons.logging|1.0.4', source: 'tools-core|7.1.0.final', target: 'org.apache.commons.logging|1.0.4' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.log4j|1.2.14', source: 'tools-core|7.1.0.final', target: 'org.apache.log4j|1.2.14' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.commons.fileupload|1.2.0', source: 'tools-core|7.1.0.final', target: 'org.apache.commons.fileupload|1.2.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.apache.commons.io|1.3.2', source: 'tools-core|7.1.0.final', target: 'org.apache.commons.io|1.3.2' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.jamonapi|2.2.0', source: 'tools-core|7.1.0.final', target: 'com.jamonapi|2.2.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-net.sourceforge.stripes|1.5.6', source: 'tools-core|7.1.0.final', target: 'net.sourceforge.stripes|1.5.6' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.joda.time|2.1', source: 'tools-core|7.1.0.final', target: 'org.joda.time|2.1' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-org.joda.time.contrib.hibernate|1.3.0', source: 'tools-core|7.1.0.final', target: 'org.joda.time.contrib.hibernate|1.3.0' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-net.sourceforge.flexjson|1.9.2.2-odl', source: 'tools-core|7.1.0.final', target: 'net.sourceforge.flexjson|1.9.2.2-odl' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-odl.com.google.common18|18.0.0.0-1-odl', source: 'tools-core|7.1.0.final', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.apt|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.apt|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.logging|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.logging|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.utility|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.utility|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.collection|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.collection|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.date|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.date|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.template|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.template|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.security|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.security|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.servlet|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.servlet|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.stripes|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.stripes|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.diagnosis|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.diagnosis|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.version|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.version|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.file|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.file|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.btree|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.btree|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.exception|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.exception|7.1.0.final' } },
{ group: 'edges', data: { id: 'tools-core|7.1.0.final-com.orchestral.common.hibernate3|7.1.0.final', source: 'tools-core|7.1.0.final', target: 'com.orchestral.common.hibernate3|7.1.0.final' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-health-common-esp|1.0.0.beta', source: 'health-common-ccda-esp|1.1.0.beta', target: 'health-common-esp|1.0.0.beta' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.consol|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.consol|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.datatypes|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.datatypes|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.rim|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.rim|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.vocab|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.vocab|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-lpg.runtime.java|2.0.17.v201004271640', source: 'health-common-ccda-esp|1.1.0.beta', target: 'lpg.runtime.java|2.0.17.v201004271640' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.eclipse.emf.common|2.6.0.v20100914-1218', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.eclipse.emf.common|2.6.0.v20100914-1218' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.eclipse.emf.ecore|2.6.1.v20100914-1218', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.eclipse.emf.ecore|2.6.1.v20100914-1218' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.eclipse.emf.ecore.xmi|2.5.0.v20100521-1846', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.eclipse.emf.ecore.xmi|2.5.0.v20100521-1846' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.eclipse.ocl|3.0.1.R30x_v201008251030', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.eclipse.ocl|3.0.1.R30x_v201008251030' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.eclipse.ocl.ecore|3.0.1.R30x_v201008251030', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.eclipse.ocl.ecore|3.0.1.R30x_v201008251030' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.ccd|1.1.0.201205021531', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.ccd|1.1.0.201205021531' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.cdt|1.1.0.201205021531', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.cdt|1.1.0.201205021531' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.consol|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.consol|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.ihe|1.1.0.201205021531', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.ihe|1.1.0.201205021531' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.cda.hitsp|1.1.0.201205021531', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.cda.hitsp|1.1.0.201205021531' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.datatypes|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.datatypes|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.rim|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.rim|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.uml.hl7.vocab|1.2.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.uml.hl7.vocab|1.2.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-org.openhealthtools.mdht.emf.runtime|1.0.0.201212201425', source: 'health-common-ccda-esp|1.1.0.beta', target: 'org.openhealthtools.mdht.emf.runtime|1.0.0.201212201425' } },
{ group: 'edges', data: { id: 'health-common-ccda-esp|1.1.0.beta-com.orchestral.health.common.ccda.esp|1.1.0.beta', source: 'health-common-ccda-esp|1.1.0.beta', target: 'com.orchestral.health.common.ccda.esp|1.1.0.beta' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-i12e-patient|8.13.0.final', source: 'Fhir-Core|1.3.0.final', target: 'i12e-patient|8.13.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-odl.com.google.common18|18.0.0.0-1-odl', source: 'Fhir-Core|1.3.0.final', target: 'odl.com.google.common18|18.0.0.0-1-odl' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-foundation|8.4.0.final', source: 'Fhir-Core|1.3.0.final', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-odl.ca.uhn.fhir_1_0|1.0.0.0-4-odl', source: 'Fhir-Core|1.3.0.final', target: 'odl.ca.uhn.fhir_1_0|1.0.0.0-4-odl' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-com.orchestral.openapi.fhir.core|1.3.0.final', source: 'Fhir-Core|1.3.0.final', target: 'com.orchestral.openapi.fhir.core|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-com.orchestral.openapi.fhir.rest.forwarder|1.3.0.final', source: 'Fhir-Core|1.3.0.final', target: 'com.orchestral.openapi.fhir.rest.forwarder|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir-Core|1.3.0.final-com.orchestral.openapi.fhir.core.conformance.ui|1.3.0.final', source: 'Fhir-Core|1.3.0.final', target: 'com.orchestral.openapi.fhir.core.conformance.ui|1.3.0.final' } },
{ group: 'edges', data: { id: 'puppet-patient-server|0.2.0.final-foundation|6.11.3.final', source: 'puppet-patient-server|0.2.0.final', target: 'foundation|6.11.3.final' } },
{ group: 'edges', data: { id: 'puppet-patient-server|0.2.0.final-common-web|7.4.0.final', source: 'puppet-patient-server|0.2.0.final', target: 'common-web|7.4.0.final' } },
{ group: 'edges', data: { id: 'puppet-patient-server|0.2.0.final-tools-extra|5.26.0.final', source: 'puppet-patient-server|0.2.0.final', target: 'tools-extra|5.26.0.final' } },
{ group: 'edges', data: { id: 'puppet-patient-server|0.2.0.final-i12e-patient|8.3.1.final', source: 'puppet-patient-server|0.2.0.final', target: 'i12e-patient|8.3.1.final' } },
{ group: 'edges', data: { id: 'puppet-patient-server|0.2.0.final-com.orchestral.puppetpatient.server|0.2.0.final', source: 'puppet-patient-server|0.2.0.final', target: 'com.orchestral.puppetpatient.server|0.2.0.final' } },
{ group: 'edges', data: { id: 'health-terminology-dev|1.0.0.beta-clinical-terminology-service|1.3.0.final', source: 'health-terminology-dev|1.0.0.beta', target: 'clinical-terminology-service|1.3.0.final' } },
{ group: 'edges', data: { id: 'health-terminology-dev|1.0.0.beta-com.orchestral.health.acceptance.terminology.mock.healthterm|1.0.0.beta', source: 'health-terminology-dev|1.0.0.beta', target: 'com.orchestral.health.acceptance.terminology.mock.healthterm|1.0.0.beta' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-Fhir1.0-Rest|1.0.1.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'Fhir1.0-Rest|1.0.1.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-Fhir-1x-Resource-Type-Handler|1.0.0.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'Fhir-1x-Resource-Type-Handler|1.0.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-Fhir-Rest|1.3.0.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'Fhir-Rest|1.3.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-Fhir-Patient|1.2.2.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'Fhir-Patient|1.2.2.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-foundation|8.4.0.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'foundation|8.4.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-cDataAccess|8.11.0.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'cDataAccess|8.11.0.final' } },
{ group: 'edges', data: { id: 'Fhir1.0-Patient|1.0.0.final-com.orchestral.openapi.fhir_1_0.patient|1.0.0.final', source: 'Fhir1.0-Patient|1.0.0.final', target: 'com.orchestral.openapi.fhir_1_0.patient|1.0.0.final' } },
{ group: 'edges', data: { id: 'yui-3|3.9.1.final-foundation|6.10.1.final', source: 'yui-3|3.9.1.final', target: 'foundation|6.10.1.final' } },
{ group: 'edges', data: { id: 'yui-3|3.9.1.final-tools-core|5.23.0.final', source: 'yui-3|3.9.1.final', target: 'tools-core|5.23.0.final' } },
{ group: 'edges', data: { id: 'yui-3|3.9.1.final-com.yahoo.yui3|3.9.1.final', source: 'yui-3|3.9.1.final', target: 'com.yahoo.yui3|3.9.1.final' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-esp-kernel|1.5.0.final', source: 'health-esp-acceptance|1.0.0.beta', target: 'esp-kernel|1.5.0.final' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-puppet-patient-server|0.2.0.final', source: 'health-esp-acceptance|1.0.0.beta', target: 'puppet-patient-server|0.2.0.final' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-configuration-admin-webservice|1.0.0.final', source: 'health-esp-acceptance|1.0.0.beta', target: 'configuration-admin-webservice|1.0.0.final' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-tools-core|7.1.0.final', source: 'health-esp-acceptance|1.0.0.beta', target: 'tools-core|7.1.0.final' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-org.joda.convert|1.3', source: 'health-esp-acceptance|1.0.0.beta', target: 'org.joda.convert|1.3' } },
{ group: 'edges', data: { id: 'health-esp-acceptance|1.0.0.beta-com.orchestral.health.acceptance.adapter.esp.rest|1.0.0.beta', source: 'health-esp-acceptance|1.0.0.beta', target: 'com.orchestral.health.acceptance.adapter.esp.rest|1.0.0.beta' } }]
